//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Xcenter.rc
//
#define IDR_MANIFEST                    1
#define IDB_EDCLOCK                     105
#define IDB_CHANBAR16                   109
#define IDB_MENUBAR                     127
#define IDR_MAINFRAME                   128
#define IDR_HOMEFRAME                   130
#define IDR_USERFRAME                   131
#define IDR_CLERKFRAME                  139
#define IDR_PAGERFRAME                  140
#define IDR_MAILFRAME                   141
#define IDR_REPORTFRAME                 142
#define IDR_MUSICFRAME                  145
#define IDR_TELECOMFRAME                146
#define IDC_HAND                        147
#define IDD_ABOUT                       148
#define IDB_NAVBAR                      150
#define IDD_EXECUTE                     160
#define IDD_SPLASH                      173
#define IDD_SETTINGS_GENERAL            174
#define IDB_PRODUCTS                    178
#define IDI_TASKPANEL                   181
#define IDI_SEARCH_FOLDER               182
#define IDD_PROFILE_USER                182
#define IDD_PRESSER_USER                183
#define IDD_PRESSER_FAX                 184
#define IDD_SETTINGS_USER               185
#define IDD_PROFILE_PLAY                187
#define IDD_SETTINGS_TRUNK              188
#define IDD_PRESSER_REC                 189
#define IDD_PRESSER_INFO                190
#define IDD_PROFILE_CORP                191
#define IDD_SETTINGS_MEETING            192
#define IDD_SETTINGS_MASTER             193
#define IDD_SETTINGS_MONITOR            195
#define IDD_PROFILE_INTER               196
#define IDD_SETTINGS_OPTIMIZE           197
#define IDD_SETTINGS_PAGER              201
#define IDD_PROFILE_FINAL               203
#define IDD_PROFILE_ANALOG              204
#define IDD_SETTINGS_CENTRIC            205
#define IDB_TASKPANEL_FOOTER            224
#define IDB_TASKBOX_CAPTION             225
#define IDB_PANEL_MARK                  262
#define IDC_HOST                        1000
#define IDC_CORPID                      1001
#define IDC_USER_NUMBER                 1002
#define IDC_USER_EXPIRE                 1003
#define IDC_DATABASE                    1004
#define IDC_USER_PRESS                  1004
#define IDC_PORT                        1005
#define IDC_USER_VIEW                   1005
#define IDC_REC_NUMBER                  1006
#define IDC_REC_EXPIRE                  1007
#define IDC_REC_PRESS                   1008
#define IDC_REC_VIEW                    1009
#define IDC_LOCAL                       1009
#define IDC_REMOTE                      1010
#define IDC_PLAY_NAME                   1012
#define IDC_TEST_ENBALE                 1012
#define IDC_PATH_BROWSE                 1013
#define IDC_PLAY_INDEX                  1014
#define IDC_USERID                      1016
#define IDC_BRIDGE                      1017
#define IDC_USER_JOB                    1017
#define IDC_LINKID                      1017
#define IDC_OUTBOUND_LIMITED            1017
#define IDC_LOCALID                     1018
#define IDC_PASSWORD                    1018
#define IDC_OUTBOUND_LIMIT              1018
#define IDC_LINK_ID                     1018
#define IDC_LOOKOUT                     1019
#define IDC_USER_BUSY                   1020
#define IDC_REC_COPY                    1021
#define IDC_PAGER_EXPIRE                1021
#define IDC_OUTBOUND_RESERVED           1021
#define IDC_REC_COPY_BROWSE             1022
#define IDC_PAGER_RETRY                 1022
#define IDC_INBOUND_LIMIT               1022
#define IDC_PAGER_INTERVAL              1023
#define IDC_TEST_CALLER                 1023
#define IDC_INBOUND_LIMITED             1023
#define IDC_TITLE                       1024
#define IDC_RING_MAX                    1024
#define IDC_TEST_PHONE                  1024
#define IDC_REC_PATH                    1025
#define IDC_REC_PATH_BROWSE             1026
#define IDC_REC_FILE                    1027
#define IDC_REC_FILE_DEFAULT            1028
#define IDC_OUT_MAXTIME                 1029
#define IDC_CALL_SPACE                  1030
#define IDC_EXECUTE_TITLE               1031
#define IDC_OUTBOUND_PHONE              1031
#define IDC_USER_ID                     1033
#define IDC_USER_HOST                   1034
#define IDC_USER_ACTION                 1035
#define IDC_USER_DESC                   1036
#define IDC_BRIDGE_PORT                 1039
#define IDC_REC_TYPE                    1040
#define IDC_USER_VNET                   1042
#define IDC_POSE_CHECK                  1043
#define IDC_POSE_NUMBER                 1044
#define IDC_TRICK_ENABLE                1045
#define IDC_REC_TRUNK                   1045
#define IDC_PATH_FAX                    1046
#define IDC_PATH_FAX_BROWSE             1047
#define IDC_USER_NO                     1048
#define IDC_PATH_REC                    1048
#define IDC_USER_TIME                   1049
#define IDC_PATH_REC_BROWSE             1049
#define IDC_MAILBOX_NAV                 1050
#define IDC_MAILBOX_OFFSET              1051
#define IDC_MODEL                       1053
#define IDC_NAME                        1054
#define IDC_PATH_BLACK                  1055
#define IDC_PATH_BLACK_BROWSE           1056
#define IDC_POSE_CALLER                 1057
#define IDC_POSE_EXCEPT                 1058
#define IDC_TIMEOUT                     1059
#define IDC_WEB                         1091
#define IDC_MAIL                        1092
#define IDC_REGISTRY                    1093
#define IDC_EXECUTE_OBJECT              1101
#define IDC_LIST                        1194
#define IDC_ADD                         1200
#define IDC_LIMITED                     1201
#define IDC_DELETE                      1204
#define IDC_EXT_LIST                    1267
#define IDC_EXT_ADD                     1268
#define IDC_EXT_REMOVE                  1269
#define IDS_SETTINGS                    8000
#define IDS_PRESSER                     8001
#define IDS_PROFILE                     8002
#define IDS_NETWORK_CONNECT             8069
#define IDS_NETWORK_CONNECTING          8070
#define IDS_NETWORK_CONNECTED           8071
#define IDS_NETWORK_DISCONNECT          8072
#define IDS_NETWORK_DISCONNECT_CONFIRM  8073
#define IDR_XML_DEFAULT                 12009
#define IDR_XML_DEFINITIONS             12010
#define ID_CHECKMARK                    32770
#define ID_TAB_HOME                     32771
#define ID_TAB_USER                     32772
#define ID_TAB_REPORT                   32773
#define ID_TAB_CONNECT                  32774
#define ID_NETWORK_CONNECT              32801
#define ID_NETWORK_DISCONNECT           32802
#define ID_REPORT_DETAILS               32821
#define ID_REPORT_PRINT                 32822
#define ID_REPORT_MUSIC                 32823
#define ID_TOOLS_SETTINGS               32831
#define ID_TOOLS_PROFILE                32832
#define ID_TOOLS_PRESSER                32833
#define ID_P2JOB_TELECOM                32841
#define ID_P2JOB_IMPORT                 32842
#define ID_P2JOB_SEARCH                 32843
#define ID_P2JOB_EXPORT                 32844
#define ID_HELP_FAQ                     32858
#define ID_TASK_CLERK                   32880
#define ID_TASK_PAGER                   32881
#define ID_TASK_MAIL                    32882
#define ID_WINDOW_TOOLBAR               57648
#define ID_WINDOW_STATUS_BAR            57649
#define ID_WINDOW_DEBUG                 57650
#define ID_WINDOW_DEBUGLOG              57651
#define IDS_QUITPROMPT                  61463

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
